services:
  - type: web
    name: app-neonatos-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run prisma:generate && npm run build && npm run prisma:migrate:deploy
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: APP_NAME
        value: APP_Neonatos
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false